version: "3.5"

services:
  mikula.dev:
    build:
      context: ./Dockerfile
      dockerfile: Dockerfile
    ports:
      - "192.168.1.121:80:80/tcp"
      - "192.168.1.121:80:80/udp"
    volumes:
      - /home/ubuntu/mikula.dev-logs/:/var/log/nginx
    environment:
      - NGINX_PORT=80
    restart: always