name: Build And Test Docker Image

on:
  pull_request:
    branches:
    - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.1.0
        with:
          log_level: DEBUG
          root: web-content/
          format: json
          css: true

      - name: Upload HTML Validator Logs
        uses: actions/upload-artifact@v2
        with:
          name: html_validator_log
          path: log.log

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.4.1
        with:
          fail: true
        env:
          LYCHEE_OUT: /tmp/lychee/out.md

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ghcr.io/pixel-yml/mikula.dev
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile

      - name: Run Snyk to check Docker image for vulnerabilities [test]
        continue-on-error: false
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          image: "ghcr.io/pixel-yml/mikula.dev:master"
          args: --file=Dockerfile --project-name=mikula.dev

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
