name: Build Test And Publish Docker Image

on:
  push:
    branches: [master]
  release:
    types:
      - published
        
jobs:
  build-test-publish:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.2.0
        with:
          fail: false
        env:
          LYCHEE_OUT: /tmp/lychee/out.md
          
      - name: Create Issue From File
        if: ${{ steps.lychee.outputs.exit_code != 0 }}
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: /tmp/lychee/out.md
          labels: report, automated issue
          
      - name: Upload Link Checker Logs
        uses: actions/upload-artifact@v2
        with:
          name: link_checker_logs
          path: /tmp/lychee/out.md
          if-no-files-found: ignore

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ghcr.io/pixel-yml/mikula.dev
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
          
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta.outputs.tags }} 
          file: ./Dockerfile

      - name: Run Snyk to check Docker image for vulnerabilities [monitor]
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          image: "ghcr.io/pixel-yml/mikula.dev:master"
          args: --file=Dockerfile --project-name=mikula.dev
          
      - name: Run Snyk to check Docker image for vulnerabilities [test]
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          image: "ghcr.io/pixel-yml/mikula.dev:master"
          args: --file=Dockerfile --project-name=mikula.dev
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
        
      - name: Push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
