name: Build And Test Docker Image

on:
  pull_request:
    branches:
    - master
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.0.0
        with:
          log_level: DEBUG
          root: web-content/
          format: text
          css: true

      - uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.log

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/pixel-yml/mikula.dev
          tag-sha: true
          tag-edge: false
          tag-latest: true
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
          
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta.outputs.tags }} 
          file: ./Dockerfile
          
      - name: Run Snyk to check Docker image for vulnerabilities [test]
        continue-on-error: false
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          image: "ghcr.io/pixel-yml/mikula.dev:master"
          args: --file=Dockerfile --project-name=mikula.dev
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
