name: trigger jenkins job
on:
  push:
    branches: [master]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://mikula.dev/jenkins"
        user: "Danylo Mikula"
        token: ${{ secrets.JENKINS_TOKEN }}
        job: "Jenkins-Deploy-Docker-Image"
