name: trigger jenkins job
on:
  push:
    branches: [master]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build single job
      uses: Mondtic/build-jenkins-job@master
      with:
        jenkins-url: ${{ secrets.JENKINS_URL }}
        jenkins-token: ${{ secrets.JENKINS_TOKEN }}
        jenkins-user: pixel-yml
        jenkins-job: Jenkins-Deploy-Docker-Image
        jenkins-job-params: "{'stringparam': 'stringvalue', 'booleanparam': false}"
        jenkins-wait-job: "no-wait"
