name: test job
on:
  push:
    branches: [master]
jobs:   
  build:    
    runs-on: ubuntu-18.04    
    env:      
      DOCKER_REGISTRY: ghcr.io      
      DOCKER_IMAGE: pixel-yml/mikula.dev       
      DOCKER_TARGET_PLATFORM: linux/arm/v7                 
    steps:    

    - name: Checkout the code       
      uses: actions/checkout@v1    

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx      
      uses: crazy-max/ghaction-docker-buildx@v3      
      with:
        buildx-version: latest
        qemu-version: latest 

    - name: Login to GHCR
      if: success()
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Prepare      
      if: success()      
      id: prepare      
      run: |        
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}        
        echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}        
        echo ::set-output name=version::${GITHUB_RUN_NUMBER}

    - name: Docker meta
      if: success()
      id: docker_meta
      uses: docker/metadata-action@v3.6.2
      with:
        images: ${{ steps.prepare.outputs.docker_image }}
        flavor: |
          latest=auto
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha

    - name: Run Buildx
      if: success()
      run: |
        docker buildx build \
          --platform ${{ steps.prepare.outputs.docker_platform }} \
          --output "type=image,push=true" \
          --tag ${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.version }} \
          --file ./Dockerfile .